" Vim settings
" Quoc-Viet Nguyen <afelion@gmail.com>
syntax on
filetype plugin indent on
colorscheme afelion

set autochdir
set smartcase

set backspace=indent,eol,start
set completeopt=longest,menuone
set wildmenu
set wildmode=list:longest,full

if has('gui_running')
  set guifont=Monospace\ 9
endif
