" Vim settings
" Quoc-Viet Nguyen <afelion@gmail.com>
syntax on
filetype on
filetype plugin on
colorscheme afelion

"enable use of mouse
if has('mouse_xterm')
  set mouse=a
endif
set autochdir

" vim features 
set nocompatible

set number " line number
set wildmenu
set wildmode=list:longest,full " comand  completion, list matches, then longest common part, then all
set backup " backups are nice
set backupdir=/tmp " but they clog cwd 

set wrap "wrap long line

"set expandtab "Spaces instead of tabs
set autoindent "Always set auto indenting on
set nosmartindent " Auto indent after a {
set smartcase
set ignorecase "ignore case

"set selectmode=mouse "select when using the mouse
set history=50 "keep 50 lines of command line history
set ruler "show the cursor position all the time
set showcmd "show (partial) commands
set incsearch "do incremental searches

"set textwidth=80

"set list "Show tab characters
set listchars=tab:>`,trail:^,nbsp:~

set showmatch
set showmode

" Turn off any bells
set novisualbell
set t_vb=

"set cmdheight=2
set laststatus=2
set statusline=[%02n]\ %f%(\ [%M%R%H]%)\ %Y\ %{&fileformat}\ %{&fileencoding}\ %L%=\ %03.3b\(%02.2B\)\ %4l,%02v\(%02c\)\ %3p%%


" Set the leader key
"let mapleader = "`" "default: \

" explorer
"nnoremap <leader>d :NERDTree<CR>
"nnoremap <leader>D :NERDTreeClose<CR>

nnoremap <leader>t :tabnew<CR>

" Tag list
"nnoremap <leader>f :TlistOpen<CR>
"nnoremap <leader>F :TlistClose<CR>

" Move lines
nnoremap <C-S-Up>    :m .-2<CR>
inoremap <C-S-Up>    <C-o>:m .-2<CR>
nnoremap <C-S-Down>  :m .+1<CR>
inoremap <C-S-Down>  <C-o>:m .+1<CR>

" win navigate
noremap  <A-Up>    <C-w>k
inoremap <A-Up>    <C-o><C-w>k
noremap  <A-Down>  <C-w>j
inoremap <A-Down>  <C-o><C-w>j
noremap  <A-Left>  <C-w>h
inoremap <A-Left>  <C-o><C-w>h
noremap  <A-Right> <C-w>l
inoremap <A-Right> <C-o><C-w>l

" backup normal moving
noremap  <C-Up> gk
inoremap <C-Up> <C-o>gk
noremap  <C-Down> gj
inoremap <C-Down> <C-o>gj

" Switch tabs
noremap  <C-Tab> gt
inoremap <C-Tab> <C-o>gt
noremap  <C-S-Tab> gT
inoremap <C-S-Tab> <C-o>gT

noremap  <A-1> 1gt
inoremap <A-1> <C-o>1gt
noremap  <A-2> 2gt
inoremap <A-2> <C-o>2gt
noremap  <A-3> 3gt
inoremap <A-3> <C-o>3gt
noremap  <A-4> 4gt
inoremap <A-4> <C-o>4gt
noremap  <A-5> 5gt
inoremap <A-5> <C-o>5gt
noremap  <A-6> 6gt
inoremap <A-6> <C-o>6gt
noremap  <A-7> 7gt
inoremap <A-7> <C-o>7gt
noremap  <A-8> 8gt
inoremap <A-8> <C-o>8gt
noremap  <A-9> 9gt
inoremap <A-9> <C-o>9gt

" resize
noremap <leader>+ <C-W>+
noremap <leader>- <C-W>-
noremap <leader>_ <C-W>_
noremap <leader>\| <C-W>\|
noremap <leader>= <C-W>=
noremap <leader>< <C-W><
noremap <leader>> <C-W>>

"move to next/previous line with same indentation
nnoremap <silent> <S-Up> k:<C-u>call search("^".matchstr(getline(line(".")+1),'\(\s*\)')."\\S", 'b')<CR>^
nnoremap <silent> <S-Down> :<C-u>call search("^".matchstr(getline(line(".")),'\(\s*\)')."\\S")<CR>^

" CTRL-C and CTRL-Insert are Copy
"map <C-S-c> "+y
"map <C-S-v> "+gP
"map <C-c> "*y<CR>

" Make shift-insert work like in Xterm
map  <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>

" map Ctrl-d to cut lines
inoremap <C-d> <C-o>dd
inoremap <C-Del> <C-o>dw
inoremap <C-Backspace> <C-o>db

" delete from cursor to end of line
"inoremap <C-S-d> <C-o>D

" map Ctrl-y to copy lines
inoremap <C-y> <C-o>yy

" map Ctrl-p to paste lines
inoremap <C-p> <C-o>p

" undo
inoremap <C-u> <C-o>u

" Disable F1
map  <F1> <nop>
imap <F1> <nop>

" save
map  <F2>  <ESC>:w<CR>
imap <F2>  <C-o>:w<CR>
"map <F3>       :set number!<CR>:set number?<CR>
"imap <F3> <C-o>:set number!<CR><C-o>:set number?<CR>

map  <F8> <ESC>:TlistToggle<CR>
imap <F8> <C-o>:TlistToggle<CR>
nmap <C-F8> :!ctags -R --c-kinds=+p --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

map  <F9> <ESC>:NERDTreeToggle<CR>
imap <F9> <C-o>:NERDTreeToggle<CR>

" highlight all
map  <F10> <ESC>:set hlsearch!<CR>:set hlsearch?<CR>
imap <F10> <C-o>:set hlsearch!<CR><C-o>:set hlsearch?<CR>

" show tab
map  <F11> <ESC>:set list!<CR>:set list?<CR>
imap <F11> <C-o>:set list!<CR><C-o>:set list?<CR>

" turn spelling on (VIM 7.0+)
map  <F12> <ESC>:setlocal spell! spelllang=en_us<CR>
imap <F12> <C-o>:setlocal spell! spelllang=en_us<CR>

" Highlight current line in insert mode.
"autocmd InsertLeave * se nocul
"autocmd InsertEnter * se cul

" Enable folding by fold markers
"set foldmethod=marker
"set foldmethod=expr
"set foldexpr=getline(v:lnum)=~'^\\s*$'&&getline(v:lnum+1)=~'\\S'?'<1':1
"set nofoldenable
"set foldcolumn=3


" Autoclose folds, when moving out of them
"set foldclose=all

" < & > to indent blocks
vnoremap < <gv
vnoremap > >gv


" C-T - new tab
"call SMap("<C-t>", ":tabnew<cr>")

" Repair wired terminal/vim settings
set backspace=start,eol,indent

"switch to directory of current file
command! CD cd %:p:h
" Coding styles
command! TSX echo 'ts:'&tabstop 'sts:'&softtabstop 'sw:'&shiftwidth 'et:'&expandtab
command! TS4 set tabstop=4 softtabstop=4 shiftwidth=4 expandtab | TSX
command! TS2 set tabstop=2 softtabstop=2 shiftwidth=2 expandtab | TSX

" insert current date
command! InsDate r !date "+\%F"
command! InsDateTime r !date "+\%F \%R:\%S"

" Remove trailing spaces
command! RemTrSp %s/\s\+$//e
" Hex mode
command! HexMode %!xxd

" select all
"noremap <C-a> ggVG
"inoremap <C-a> <ESC>ggVG

" write sudo
command! W w !sudo tee % > /dev/null

command! DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis | wincmd p | diffthis

" ctags
set tags=./tags;
nmap <C-\> <C-W><C-]><C-w>T

" tab/indent by file types
"set tabstop=4
"set shiftwidth=4
"autocmd Filetype {c,h}   setlocal expandtab
"autocmd Filetype h   setlocal expandtab

" DoxygenToolkit
let g:DoxygenToolkit_authorName="vietnq"

if has("autocmd") && exists("+omnifunc")
	autocmd Filetype *
	\if &omnifunc == "" |
		\setlocal omnifunc=syntaxcomplete#Complete |
	\endif
endif
set completeopt=longest,menuone " show preview of function prototype


" Latex Suite
" win32 users will need to have 'shellslash' set so that latex
" can be called correctly.
"set shellslash

" grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*
"
let g:Imap_UsePlaceHolders=0
" leave F1-F4 unmapped
let g:Tex_HotKeyMappings=""
let g:Tex_SmartKeyQuote=0
let g:Tex_SmartKeyDot=0
let g:Tex_AutoFolding=0

" NERDTree
let g:NERDTreeWinSize=24

if has('gui_running')
  set guioptions=gmr
  set guifont=Monospace\ 9
  set colorcolumn=80
endif
